apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-coldstart
spec:
  replicas: 0
  selector:
    matchLabels:
      app: gpu-coldstart
  template:
    metadata:
      labels:
        app: gpu-coldstart
    spec:
      runtimeClassName: nvidia # for gpu drivers access
      containers:
        - name: gpu-coldstart
          image: gpu-demo:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TRANSFORMERS_CACHE
              value: /models/hf
            - name: HF_HOME
              value: /models/hf
            - name: TOKENIZERS_PARALLELISM
              value: "false"
            - name: HF_HUB_DISABLE_TELEMETRY
              value: "1"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
              cpu: "1"
              memory: "2Gi"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: gpu-coldstart
spec:
  selector:
    app: gpu-coldstart
  ports:
    - port: 80
      targetPort: 8000
