apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  runtimeClassName: nvidia
  containers:
  - name: cuda
    image: nvidia/cuda:13.0.1-runtime-ubuntu24.04
    command: ["/bin/bash", "-c", "--"]
    args: ["nvidia-smi; sleep infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
